apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Developer portal for the home Talos cluster
  annotations:
    github.com/project-slug: georg-nikola/backstage
    backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=backstage
    argocd/app-name: backstage
spec:
  type: website
  lifecycle: production
  owner: platform
  system: home-cluster
